### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by kozytominaga** [AppLovin/SDK-Network-Adapters#119]
I got an error in google play console pre-launch report.
Is this a known issue?

sdk:
    implementation 'com.google.android.gms:play-services-ads:20.6.0'
    implementation 'com.google.ads.mediation:applovin:11.3.3.0'

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1441)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1475)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1473)
	at java.util.HashMap.putMapEntries(HashMap.java:511)
	at java.util.HashMap.<init>(HashMap.java:489)
	at com.applovin.impl.sdk.p.b(Unknown Source:4)
	at com.applovin.impl.sdk.e.i.b(Unknown Source:283)
	at com.applovin.impl.sdk.e.i.run(Unknown Source:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by thomasmso** [comment]
Thanks for reporting it. How often is this crash occurring for you?

**Comment by kozytominaga** [comment]
Thank you for your quick reply.
This error occurred only once in pre-launch report.  
(Google Pixel 5
1080x2340
Android 11（SDK 30）
7,680 MB
ARM64_V8)
I have never encountered this error on my own device.

thanks.

**Comment by thomasmso** [comment]
We'll look into it but seeing how rare it is, it's likely not going to be anytime soon.

**Comment by kozytominaga** [comment]
Thank you.
I look forward to hearing form you.

**Comment by guowei0306** [comment]
Hello, this crash has been resolved in latest AppLovin SDK 11.5.0. See release note here: https://github.com/AppLovin/AppLovin-MAX-SDK-Android/releases

Thank you for your patience!
